[package]
name = "CEX-Order-Book"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = {version = "0.12.15", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
websocket = "0.27.1"
